<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Andreas Niekler, Gregor Wiedemann" />

<meta name="date" content="2017-10-02" />

<title>Tutorial 6: Topic Models</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Intro</a>
</li>
<li>
  <a href="Tutorial_1_Data_acquisition.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 1
  </a>
</li>
<li>
  <a href="Tutorial_2_Read_data_Zipf.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 2
  </a>
</li>
<li>
  <a href="Tutorial_3_Frequency.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 3
  </a>
</li>
<li>
  <a href="Tutorial_4_Term_extraction.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 4
  </a>
</li>
<li>
  <a href="Tutorial_5_Co-occurrence.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 5
  </a>
</li>
<li>
  <a href="Tutorial_6_Topic_Models.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 6
  </a>
</li>
<li>
  <a href="Tutorial_7_Klassifikation.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 7
  </a>
</li>
<li>
  <a href="Tutorial_8_NER_POS.html">
    <span class="ion ion-android-bulb"></span>
     
    Tutorial 8
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Tutorial 6: Topic Models</h1>
<h4 class="author"><em>Andreas Niekler, Gregor Wiedemann</em></h4>
<h4 class="date"><em>2017-10-02</em></h4>

</div>


<p>This exercise demonstrates the use of topic models on a text corpus for the extraction of latent semantic contexts in the documents. In this exercise we will:</p>
<ol style="list-style-type: decimal">
<li>Read in and preprocess text data,</li>
<li>Calculate a topic model using the R package <em>topmicmodels</em> and analyze its results in more detail,</li>
<li>Visualize the results from the calculated model and</li>
<li>Select documents based on their topic composition.</li>
</ol>
<p>The process starts as usual with the reading of the corpus data. Change to your working directory, create a new R script, load the tm-package and define a few already known default variables.</p>
<pre class="r"><code># setwd(&quot;Your work directory&quot;)
options(stringsAsFactors = FALSE)
library(tm)
require(topicmodels)</code></pre>
<p>For text preprocessing, we remove stopwords, since they tend to occur as “noise” in the estimated topics of the LDA model.</p>
<pre class="r"><code>textdata &lt;- read.csv(&quot;data/sotu.csv&quot;, sep = &quot;;&quot;, encoding = &quot;UTF-8&quot;)
english_stopwords &lt;- readLines(&quot;resources/stopwords_en.txt&quot;, encoding = &quot;UTF-8&quot;)

# Create corpus object
m &lt;- list(ID = &quot;id&quot;, content = &quot;text&quot;, DateTimeStamp = &quot;date&quot;)
myReader &lt;- readTabular(mapping = m)
corpus &lt;- Corpus(DataframeSource(textdata), readerControl = list(reader = myReader))

# Preprocessing chain
processedCorpus &lt;- tm_map(corpus, removePunctuation, preserve_intra_word_dashes = TRUE)
processedCorpus &lt;- tm_map(processedCorpus, removeNumbers)
processedCorpus &lt;- tm_map(processedCorpus, content_transformer(tolower))
processedCorpus &lt;- tm_map(processedCorpus, removeWords, english_stopwords)
processedCorpus &lt;- tm_map(processedCorpus, stemDocument, language = &quot;en&quot;)
processedCorpus &lt;- tm_map(processedCorpus, stripWhitespace)</code></pre>
<div id="model-calculation" class="section level1">
<h1><span class="header-section-number">1</span> Model calculation</h1>
<p>After the preprocessing, we have two corpus objects: <code>processedCorpus</code>, on which we calculate an LDA topic model <span class="citation">[1]</span>. To this end, stopwords were removed, words were stemmed and converted to lowercase letters and special characters were removed. The second Corpus object <code>corpus</code> serves to be able to view the original texts and thus to facilitate a qualitative control of the topic model results.</p>
<p>We now calculate a topic model on the <code>processedCorpus</code>. For this purpose, a DTM of the corpus is created. In this case, we only want to consider terms that occur with a certain minimum frequency in the body. This is primarily used to speed up the model calculation.</p>
<pre class="r"><code># compute document term matrix with terms &gt;= minimumFrequency
minimumFrequency &lt;- 5
DTM &lt;- DocumentTermMatrix(processedCorpus, control = list(bounds = list(global = c(minimumFrequency, Inf))))

# have a look at the number of documents and terms in the matrix
dim(DTM)</code></pre>
<pre><code>## [1]  231 7673</code></pre>
<p>As an unsupervised machine learning method, topic models are suitable for the exploration of data. The calculation of topic models aims to determine the proportionate composition of a fixed number of topics in the documents of a collection. It is useful to experiment with different parameters in order to find the most suitable parameters for your own analysis needs.</p>
<p>For parameterized models such as Latent Dirichlet Allocation (LDA), the number of topics <code>K</code> is the most important parameter to define in advance. How an optimal <code>K</code> should be selected depends on various factors. If <code>K</code> is too small, the collection is divided into a few very general semantic contexts. If <code>K</code> is too large, the collection is divided into too many topics of which some may overlap and others are hardly interpretable.</p>
<p>For our first analysis we choose a thematic “resolution” of <code>K = 20</code> topics. In contrast to a resolution of 100 or more, this number of topics can be evaluated qualitatively very easy.</p>
<pre class="r"><code># load package topicmodels
require(topicmodels)
# number of topics
K &lt;- 20
# set random number generator seed
set.seed(9161)
# compute the LDA model, inference via 1000 iterations of Gibbs sampling
topicModel &lt;- LDA(DTM, K, method=&quot;Gibbs&quot;, control=list(iter = 500, verbose = 25))</code></pre>
<p>Depending on the size of the vocabulary, the collection size and the number K, the inference of topic models can take a very long time. This calculation may take several minutes. If it takes too long, reduce the vocabulary in the DTM by increasing the minimum frequency in the previous step.</p>
<p>The topic model inference results in two (approximate) posterior probability distributions: a distribution <code>theta</code> over K topics within each document and a distribution <code>beta</code> over V terms within each topic, where V represents the length of the vocabulary of the collection (V = 7673). Let’s take a closer look at these results:</p>
<pre class="r"><code># have a look a some of the results (posterior distributions)
tmResult &lt;- posterior(topicModel)
# format of the resulting object
attributes(tmResult)</code></pre>
<pre><code>## $names
## [1] &quot;terms&quot;  &quot;topics&quot;</code></pre>
<pre class="r"><code>nTerms(DTM)              # lengthOfVocab</code></pre>
<pre><code>## [1] 7673</code></pre>
<pre class="r"><code># topics are probability distribtions over the entire vocabulary
beta &lt;- tmResult$terms   # get beta from results
dim(beta)                # K distributions over nTerms(DTM) terms</code></pre>
<pre><code>## [1]   20 7673</code></pre>
<pre class="r"><code>rowSums(beta)            # rows in beta sum to 1</code></pre>
<pre><code>##  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 
##  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1</code></pre>
<pre class="r"><code>nDocs(DTM)               # size of collection</code></pre>
<pre><code>## [1] 231</code></pre>
<pre class="r"><code># for every document we have a probaility distribution of its contained topics
theta &lt;- tmResult$topics 
dim(theta)               # nDocs(DTM) distributions over K topics</code></pre>
<pre><code>## [1] 231  20</code></pre>
<pre class="r"><code>rowSums(theta)[1:10]     # rows in theta sum to 1</code></pre>
<pre><code>##  1  2  3  4  5  6  7  8  9 10 
##  1  1  1  1  1  1  1  1  1  1</code></pre>
<p>Let’s take a look at the 10 most likely terms within the term probabilities <code>beta</code> of the inferred topics (only the first 8 are shown below).</p>
<pre class="r"><code>terms(topicModel, 10)</code></pre>
<pre><code>##       Topic 1    Topic 2    Topic 3   Topic 4     Topic 5    Topic 6    
##  [1,] &quot;war&quot;      &quot;govern&quot;   &quot;nation&quot;  &quot;program&quot;   &quot;world&quot;    &quot;america&quot;  
##  [2,] &quot;men&quot;      &quot;duti&quot;     &quot;war&quot;     &quot;year&quot;      &quot;nation&quot;   &quot;american&quot; 
##  [3,] &quot;american&quot; &quot;peopl&quot;    &quot;part&quot;    &quot;nation&quot;    &quot;free&quot;     &quot;freedom&quot;  
##  [4,] &quot;forc&quot;     &quot;time&quot;     &quot;peac&quot;    &quot;increas&quot;   &quot;freedom&quot;  &quot;nation&quot;   
##  [5,] &quot;enemi&quot;    &quot;regard&quot;   &quot;forc&quot;    &quot;feder&quot;     &quot;peopl&quot;    &quot;secur&quot;    
##  [6,] &quot;fight&quot;    &quot;hope&quot;     &quot;author&quot;  &quot;congress&quot;  &quot;defens&quot;   &quot;countri&quot;  
##  [7,] &quot;unit&quot;     &quot;part&quot;     &quot;million&quot; &quot;state&quot;     &quot;strength&quot; &quot;world&quot;    
##  [8,] &quot;peac&quot;     &quot;justic&quot;   &quot;unit&quot;    &quot;develop&quot;   &quot;econom&quot;   &quot;terrorist&quot;
##  [9,] &quot;product&quot;  &quot;question&quot; &quot;debt&quot;    &quot;continu&quot;   &quot;militari&quot; &quot;peopl&quot;    
## [10,] &quot;part&quot;     &quot;make&quot;     &quot;commerc&quot; &quot;administr&quot; &quot;effort&quot;   &quot;terror&quot;   
##       Topic 7     Topic 8   
##  [1,] &quot;state&quot;     &quot;state&quot;   
##  [2,] &quot;constitut&quot; &quot;unit&quot;    
##  [3,] &quot;union&quot;     &quot;congress&quot;
##  [4,] &quot;power&quot;     &quot;govern&quot;  
##  [5,] &quot;peopl&quot;     &quot;great&quot;   
##  [6,] &quot;congress&quot;  &quot;year&quot;    
##  [7,] &quot;territori&quot; &quot;act&quot;     
##  [8,] &quot;presid&quot;    &quot;treati&quot;  
##  [9,] &quot;law&quot;       &quot;power&quot;   
## [10,] &quot;republ&quot;    &quot;duti&quot;</code></pre>
<p>For the next steps, we want to give the topics more descriptive names than just numbers. Therefore, we simply concatenate the five most likely terms of each topic to a string that represents a pseudo-name for each topic.</p>
<pre class="r"><code>top5termsPerTopic &lt;- terms(topicModel, 5)
topicNames &lt;- apply(top5termsPerTopic, 2, paste, collapse=&quot; &quot;)</code></pre>
</div>
<div id="visualization-of-words-and-topics" class="section level1">
<h1><span class="header-section-number">2</span> Visualization of Words and Topics</h1>
<p>Although wordclouds may not be optimal for scientific purposes they can provide a quick visual overview of a set of terms. Let’s look at some topics as wordcloud.</p>
<p>In the following code, you can change the variable <strong>topicToViz</strong> with values between 1 and 20 to display other topics.</p>
<pre class="r"><code>require(wordcloud)
# visualize topics as word cloud
topicToViz &lt;- 11 # change for your own topic of interest
topicToViz &lt;- grep(&#39;mexico&#39;, topicNames)[1] # Or select a topic by a term contained in its name
# select to 40 most probable terms from the topic by sorting the term-topic-probability vector in decreasing order
top40terms &lt;- sort(tmResult$terms[topicToViz,], decreasing=TRUE)[1:40]
words &lt;- names(top40terms)
# extract the probabilites of each of the 40 terms
probabilities &lt;- sort(tmResult$terms[topicToViz,], decreasing=TRUE)[1:40]
# visualize the terms as wordcloud
mycolors &lt;- brewer.pal(8, &quot;Dark2&quot;)
wordcloud(words, probabilities, random.order = FALSE, color = mycolors)</code></pre>
<p><img src="Tutorial_6_Topic_Models_files/figure-html/unnamed-chunk-5-1.png" width="384" style="display: block; margin: auto;" /></p>
<p>Let us now look more closely at the distribution of topics within individual documents. To this end, we visualize the distribution in 3 sample documents.</p>
<p>Let us first take a look at the contents of three sample documents:</p>
<pre class="r"><code>exampleIds &lt;- c(1, 100, 200)
lapply(corpus[exampleIds], as.character)</code></pre>
<pre><code>## [1] &quot;1: Fellow-Citizens of the Senate and House of Representatives:\n\nI embrace with great satisfaction the opportunity which now presents itself\nof congratulating you on the present favorable prospects of our public\naffairs. The recent accession of the important state of North Carolina to\nthe Constitution of the United States (of which official information has\nbeen received), the rising credit and respect...&quot;</code></pre>
<pre><code>## [1] &quot;100: To the Congress of the United States:\n\nAs you assemble for the discharge of the duties you have assumed as the\nrepresentatives of a free and generous people, your meeting is marked by an\ninteresting and impressive incident. With the expiration of the present\nsession of the Congress the first century of our constitutional existence\nas a nation will be completed.\n\nOur survival for one hundred years ...&quot;</code></pre>
<pre><code>## [1] &quot;200: Mr. Speaker, Mr. President, distinguished Members of Congress, honored\nguests, and fellow citizens:\n\nMay I congratulate all of you who are Members of this historic 100th\nCongress of the United States of America. In this 200th anniversary year of\nour Constitution, you and I stand on the shoulders of giants--men whose\nwords and deeds put wind in the sails of freedom. However, we must always\nremember...&quot;</code></pre>
<p>After looking into the documents, we visualize the topic distributions within the documents.</p>
<pre class="r"><code># load libraries for visualization
library(&quot;reshape2&quot;)
library(&quot;ggplot2&quot;)
N &lt;- length(exampleIds)
# get topic proportions form example documents
topicProportionExamples &lt;- theta[exampleIds,]
colnames(topicProportionExamples) &lt;- topicNames
vizDataFrame &lt;- melt(cbind(data.frame(topicProportionExamples), document = factor(1:N)), variable.name = &quot;topic&quot;, id.vars = &quot;document&quot;)  

ggplot(data = vizDataFrame, aes(topic, value, fill = document), ylab = &quot;proportion&quot;) + 
  geom_bar(stat=&quot;identity&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +  
  coord_flip() +
  facet_wrap(~ document, ncol = N)</code></pre>
<p><img src="Tutorial_6_Topic_Models_files/figure-html/unnamed-chunk-8-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="topic-distributions" class="section level1">
<h1><span class="header-section-number">3</span> Topic distributions</h1>
<p>The figure above shows how topics within a document are distributed according to the model. In the current model all three documents show at least a small percentage of each topic. However, two to three topics dominate each document.</p>
<p>The topic distribution within a document can be controlled with the <em>Alpha</em>-parameter of the model. Higher alpha priors for topics result in an even distribution of topics within a document. Low alpha priors ensure that the inference process distributes the probability mass on a few topics for each document.</p>
<p>In the previous model calculation the alpha-prior was automatically estimated in order to fit to the data (highest overall probability of the model). However, this automatic estimate does not necessarily correspond to the results that one would like to have as an analyst. Depending on our analysis interest, we might be interested in a more peaky/more even distribution of topics in the model.</p>
<p>Now let us change the alpha prior to a lower value to see how this affects the topic distributions in the model.</p>
<pre class="r"><code># see alpha from previous model
attr(topicModel, &quot;alpha&quot;) </code></pre>
<pre><code>## [1] 2.5</code></pre>
<pre class="r"><code>topicModel2 &lt;- LDA(DTM, K, method=&quot;Gibbs&quot;, control=list(iter = 500, verbose = 25, alpha = 0.2))
tmResult &lt;- posterior(topicModel2)
theta &lt;- tmResult$topics
beta &lt;- tmResult$terms
topicNames &lt;- apply(terms(topicModel2, 5), 2, paste, collapse = &quot; &quot;)  # reset topicnames</code></pre>
<p>Now visualize the topic distributions in the three documents again. What are the differences in the distribution structure?</p>
<pre class="r"><code># get topic proportions form example documents
topicProportionExamples &lt;- theta[exampleIds,]
colnames(topicProportionExamples) &lt;- topicNames
vizDataFrame &lt;- melt(cbind(data.frame(topicProportionExamples), document = factor(1:N)), variable.name = &quot;topic&quot;, id.vars = &quot;document&quot;)  

ggplot(data = vizDataFrame, aes(topic, value, fill = document), ylab = &quot;proportion&quot;) + 
  geom_bar(stat=&quot;identity&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +  
  coord_flip() +
  facet_wrap(~ document, ncol = N)</code></pre>
<p><img src="Tutorial_6_Topic_Models_files/figure-html/unnamed-chunk-10-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="topic-ranking" class="section level1">
<h1><span class="header-section-number">4</span> Topic ranking</h1>
<p>First, we try to get a more meaningful order of top terms per topic by re-ranking them with a specific score <span class="citation">[2]</span>. The idea of re-ranking terms is similar to the idea of TF-IDF. The more a term appears in top levels w.r.t. its probability, the less meaningful it is to describe the topic. Hence, the scoring advanced favors terms to describe a topic.</p>
<pre class="r"><code># re-rank top topic terms for topic names
topicNames &lt;- apply(lda::top.topic.words(beta, 5, by.score = T), 2, paste, collapse = &quot; &quot;)</code></pre>
<p>What are the defining topics within a collection? There are different approaches to find out which can be used to bring the topics into a certain order.</p>
<p><strong>Approach 1:</strong> We sort topics according to their probability within the entire collection:</p>
<pre class="r"><code># What are the most probable topics in the entire collection?
topicProportions &lt;- colSums(theta) / nDocs(DTM)  # mean probablities over all documents
names(topicProportions) &lt;- topicNames     # assign the topic names we created before
sort(topicProportions, decreasing = TRUE) # show summed proportions in decreased order</code></pre>
<pre><code>##  [1] &quot;0.22522 : govern state public interest subject&quot; 
##  [2] &quot;0.10318 : world nation free peac peopl&quot;         
##  [3] &quot;0.09655 : america work job make year&quot;           
##  [4] &quot;0.08841 : nation govern congress system work&quot;   
##  [5] &quot;0.08103 : nation unit object vessel part&quot;       
##  [6] &quot;0.07425 : state mexico unit war amount&quot;         
##  [7] &quot;0.05298 : program growth feder energi propos&quot;   
##  [8] &quot;0.03478 : unit recommend cuba congress nation&quot;  
##  [9] &quot;0.02809 : govern unit american state treati&quot;    
## [10] &quot;0.02794 : make men matter ship peac&quot;            
## [11] &quot;0.02512 : terrorist america iraq terror fight&quot;  
## [12] &quot;0.0244 : state constitut union right principl&quot;  
## [13] &quot;0.02263 : program dollar fiscal million billion&quot;
## [14] &quot;0.02096 : manufactur present price cost tariff&quot; 
## [15] &quot;0.01866 : public agricultur method board cent&quot;  
## [16] &quot;0.01798 : year fiscal silver indian report&quot;     
## [17] &quot;0.01767 : war enemi forc fight victori&quot;         
## [18] &quot;0.01605 : law man nation corpor work&quot;           
## [19] &quot;0.0141 : bank gold currenc note circul&quot;         
## [20] &quot;0.01 : constitut california slaveri peopl slave&quot;</code></pre>
<p>We recognize some topics that are way more likely to occur in the corpus than others. These describe rather general thematic coherences. Other topics correspond more to specific contents.</p>
<p><strong>Approach 2:</strong> We count how often a topic appears as a primary topic within a document. This method is also called Rank-1.</p>
<pre class="r"><code>countsOfPrimaryTopics &lt;- rep(0, K)
names(countsOfPrimaryTopics) &lt;- topicNames
for (i in 1:nDocs(DTM)) {
  topicsPerDoc &lt;- theta[i, ] # select topic distribution for document i
  # get first element position from ordered list
  primaryTopic &lt;- order(topicsPerDoc, decreasing = TRUE)[1] 
  countsOfPrimaryTopics[primaryTopic] &lt;- countsOfPrimaryTopics[primaryTopic] + 1
}
sort(countsOfPrimaryTopics, decreasing = TRUE)</code></pre>
<pre><code>##  [1] &quot;87 : govern state public interest subject&quot;   
##  [2] &quot;30 : world nation free peac peopl&quot;           
##  [3] &quot;29 : america work job make year&quot;             
##  [4] &quot;20 : nation govern congress system work&quot;     
##  [5] &quot;13 : nation unit object vessel part&quot;         
##  [6] &quot;10 : govern unit american state treati&quot;      
##  [7] &quot;8 : terrorist america iraq terror fight&quot;     
##  [8] &quot;7 : law man nation corpor work&quot;              
##  [9] &quot;6 : make men matter ship peac&quot;               
## [10] &quot;6 : program growth feder energi propos&quot;      
## [11] &quot;3 : state mexico unit war amount&quot;            
## [12] &quot;3 : year fiscal silver indian report&quot;        
## [13] &quot;3 : war enemi forc fight victori&quot;            
## [14] &quot;2 : public agricultur method board cent&quot;     
## [15] &quot;1 : unit recommend cuba congress nation&quot;     
## [16] &quot;1 : bank gold currenc note circul&quot;           
## [17] &quot;1 : manufactur present price cost tariff&quot;    
## [18] &quot;1 : program dollar fiscal million billion&quot;   
## [19] &quot;0 : state constitut union right principl&quot;    
## [20] &quot;0 : constitut california slaveri peopl slave&quot;</code></pre>
<p>We see that sorting topics by the Rank-1 method places topics with rather specific thematic coherences in upper ranks of the list.</p>
<p>This sorting of topics can be used for further analysis steps such as the semantic interpretation of topics found in the collection, the analysis of time series of the most important topics or the filtering of the original collection based on specific sub-topics.</p>
</div>
<div id="filtering-documents" class="section level1">
<h1><span class="header-section-number">5</span> Filtering documents</h1>
<p>The fact that a topic model conveys of topic probabilities for each document makes it possible to use it for thematic filtering of a collection. AS filter we select only those documents which exceed a certain threshold of their probability value for certain topics (for example, each document which contains topic <code>X</code> to more than 20 percent).</p>
<p>In the following, we will select documents based on their topic content and display the resulting document quantity over time.</p>
<pre class="r"><code>topicToFilter &lt;- 6  # you can set this manually ...
# ... or have it selected by a term in the topic name (e.g. &#39;iraq&#39;)
topicToFilter &lt;- grep(&#39;iraq&#39;, topicNames)[1] 
topicThreshold &lt;- 0.2
selectedDocumentIndexes &lt;- which(theta[, topicToFilter] &gt;= topicThreshold)
filteredCorpus &lt;- corpus[selectedDocumentIndexes]

# show length of filtered corpus
filteredCorpus</code></pre>
<pre><code>## &lt;&lt;VCorpus&gt;&gt;
## Metadata:  corpus specific: 0, document level (indexed): 0
## Content:  documents: 8</code></pre>
<p>Our filtered corpus contains 8 documents related to the topic 2 to at least 20 %.</p>
</div>
<div id="topic-proportions-over-time" class="section level1">
<h1><span class="header-section-number">6</span> Topic proportions over time</h1>
<p>In a last step, we provide a distant view on the topics in the data over time. For this, we aggregate mean topic proportions per decade of all SOTU speeches. These aggregated topic proportions can then be visualized, e.g. as a bar plot.</p>
<pre class="r"><code># append decade information for aggregation
textdata$decade &lt;- paste0(substr(textdata$date, 0, 3), &quot;0&quot;)
# get mean topic proportions per decade
topic_proportion_per_decade &lt;- aggregate(theta, by = list(decade = textdata$decade), mean)
# set topic names to aggregated columns
colnames(topic_proportion_per_decade)[2:(K+1)] &lt;- topicNames

# reshape data frame
vizDataFrame &lt;- melt(topic_proportion_per_decade, id.vars = &quot;decade&quot;)

# plot topic proportions per deacde as bar plot
require(pals)
ggplot(vizDataFrame, aes(x=decade, y=value, fill=variable)) + 
  geom_bar(stat = &quot;identity&quot;) + ylab(&quot;proportion&quot;) + 
  scale_fill_manual(values = paste0(alphabet(20), &quot;FF&quot;), name = &quot;decade&quot;) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))</code></pre>
<p><img src="Tutorial_6_Topic_Models_files/figure-html/unnamed-chunk-16-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>The visualization shows that topics around the relation between the federal government and the states as well as inner conflicts clearly dominate the first decades. Security issues and the economy are the most important topics of recent SOTU addresses.</p>
</div>
<div id="remark" class="section level1">
<h1><span class="header-section-number">7</span> Remark</h1>
<p>The 231 SOTU addresses are rather long documents. Documents lengths clearly affects the results of topic modeling. For very short texts (e.g. Twitter posts) or very long texts (e.g. books), it can make sense to concatenate/split single documents to receive longer/shorter textual units for modeling.</p>
<p>For the SOTU speeches for instance, it may be beneficial to model on paragraphs instead of entire speeches. By manual inspection / qualitative inspection of the results you can check if this procedure yields better (interpretable) topics.</p>
</div>
<div id="optional-exercises" class="section level1">
<h1><span class="header-section-number">8</span> Optional exercises</h1>
<ol style="list-style-type: decimal">
<li>Create a list of all documents that have a thematic context with <em>economy</em>.</li>
<li>Repeat the exercises with a different K value (e.g., K = 5, 30, 50). What do you think of the results?</li>
<li>Split the original text source into paragraphs (e.g. use <code>strsplit(textdata$text, &quot;\n\n&quot;)</code>) and compute a topic model on paragraphs instead of full speeches. How does the smaller context unit affect the result?</li>
</ol>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-blei_latent_2003">
<p>1. Blei, D., Ng, A., Jordan, M.: Latent dirichlet allocation. The Journal of Machine Learning Research. 3, 993–1022 (2003).</p>
</div>
<div id="ref-Chang.2012">
<p>2. Chang, J.: Lda: Collapsed gibbs sampling methods for topic models. (2012).</p>
</div>
</div>
</div>

<p>2017, Andreas Niekler and Gregor Wiedemann. GPLv3. <a href="https://tm4ss.github.io">tm4ss.github.io</a></p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
